### ISSUE TITLE
Development server fails due to wagmi config issue

### ISSUE THREAD

**Issue by rajkharvar** [Dhaiwat10/create-web3-frontend#14]
## Issue
![Screenshot 2022-06-18 at 2 02 18 PM](https://user-images.githubusercontent.com/39342288/174429753-f2fd0d3c-8088-4d0f-9b14-ac0901b95508.png)

## Steps to reproduce
1. `npx create-web3-frontend my-app`
2. `cd my-app`
3. `yarn dev`

## Cause of issue
This can happen while upgrading wagmi from 0.3 to 0.4.
More reference can be found [here](https://wagmi.sh/docs/migrating-to-03#wagmiconnectorswalletlink-was-renamed)

**Comment by Dhaiwat10** [comment]
Hey, I think you might be using an old version of `create-web3-frontend`. Try running `npx create-web3-frontend@1.2.0`

**Comment by rajkharvar** [comment]
Ok. that works.
Thanks @Dhaiwat10
