### ISSUE TITLE
update to newest wagmi & rainbowkit

### ISSUE THREAD

**Issue by Geczy** [Dhaiwat10/create-web3-frontend#15]
title

**Comment by arihantbansal** [comment]
wagmi has updated to v0.6.0 which has brought a lot of breaking changes in its API. Need an update on this template.

**Comment by Dhaiwat10** [comment]
will do this whne i get time guys. PRs are always welcome if you need this urgently! :)

**Comment by michaellyons** [comment]
@Dhaiwat10 @Geczy https://github.com/Dhaiwat10/create-web3-frontend/pull/16

**Comment by Geczy** [comment]
love it, thank you for updating
